name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use latest Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm run test:unit
      - name: Integration Tests
        run: npm run test:int
        env:
          CI: 'true'
          AZURE_DEVOPS_ORG_URL: ${{ secrets.AZURE_DEVOPS_ORG_URL }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_DEFAULT_PROJECT: ${{ secrets.AZURE_DEVOPS_DEFAULT_PROJECT }}
          AZURE_DEVOPS_DEFAULT_REPOSITORY: eShopOnWeb
          AZURE_DEVOPS_AUTH_METHOD: pat
      - name: E2E Tests
        run: npm run test:e2e
        env:
          CI: 'true'
          AZURE_DEVOPS_ORG_URL: ${{ secrets.AZURE_DEVOPS_ORG_URL }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_DEFAULT_PROJECT: ${{ secrets.AZURE_DEVOPS_DEFAULT_PROJECT }}
          AZURE_DEVOPS_DEFAULT_REPOSITORY: eShopOnWeb
          AZURE_DEVOPS_AUTH_METHOD: pat
